def lazy_fixture(names: str | list[str]) -> LazyFixture | list[LazyFixture]: ...

class LazyFixture:
    def __init__(self, name: str) -> None: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: object) -> bool: ...
